config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/send_message', to: 'chat_page#send_message', as: 'send_message'
  root "chat_page#index"
  get 'chat_page/index'
  get 'chat_page/by_user', to: 'chat_page#by_user', as: 'by_user'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chat_page_controller.rb
require 'telegram/bot'
class ChatPageController < ApplicationController
    def index 
        @messages = Message.all
        TelegramListenJob.perform_later
    end

    #send and save image URL
    def image_present
        #replace token with your own
        token = '6209842775:AAEYa6OjRdy6C3NJssQR6oa_woxAFVMvnQ4'
        client = Telegram::Bot::Client.new(token)  
        image = params[:image]
        user_id = params[:user_id]
        content_type = image.content_type
        response = client.api.send_photo(chat_id: user_id, photo: Faraday::UploadIO.new(image.path, content_type)) 
        file_id = response['result']['photo'].last['file_id']
        file = client.api.get_file(file_id: file_id)
        file_path = file['result']['file_path']
        image_url = "https://api.telegram.org/file/bot#{token}/#{file_path}"
        Message.create(image_url: image_url, first_name: 'bot', user_name: 'botson', user_id: user_id)
        redirect_to by_user_path(user_id: user_id)
    end

    #send message (text or image)
    def send_message
        #replace token with your own
        token = '6209842775:AAEYa6OjRdy6C3NJssQR6oa_woxAFVMvnQ4'
        message_text = params[:message_text]
        user_id = params[:user_id]
        image = params[:image]
        client = Telegram::Bot::Client.new(token)  
        if message_text.present?
            if image.present?
                image_present
            end
            client.api.send_message(chat_id: user_id, text: message_text)
            message = Message.create(text: message_text, user_id: user_id, first_name: 'bot', user_name: 'botson')
            redirect_to by_user_path(user_id: user_id)  
        elsif image.present? 
            image_present
        end
    end
    
    def by_user
        @messages = Message.all
        @user_id = @messages.group_by( &:user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_page_helper.rb
module ChatPageHelper
end

app/views/chat_page/by_user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bot chat</title>

 <link rel="stylesheet" type="text/css" href="<%= asset_path('chat_app.css') %>"> 

</head>
<body>
  <div class="outer-container">
    <div class="users-list",id="message-list">
    
      <% Message.pluck(:user_id).uniq.each do |user_id| %>
  
        <li>
        <button>
          <%= link_to "#{ Message.where.not(user_name: "botson").where(user_id: user_id).order(created_at: :desc).pluck(:user_name).first || "Unknown" }", by_user_path(user_id: user_id), class: "link-primary" %>
        </button>
        </li>
      <% end %>
    </div>
    <div class="chat-container">
      <span class="user-name">
        <%= @user_id[params[:user_id].to_i].reverse.find { |message| message.user_name != "botson" }&.user_name || "Unknown" %>
      </span>

      <ul class="message-lists" id="message-list">
        <% @user_id.each do |hash| %>
          <% hash[1].each do |message| %>
            <% if message.user_id == params[:user_id].to_i %>
              <li class="message <%= message.user_name == "botson" ? "botson" : "other" %>" style="flex-direction: <%= message.user_name == "botson" ? "row-reverse" : "row" %>;">
              <%if message.text.present?%>
                <span><%= message.text %></span>
                <%elsif message.image_url.present?%>
                <img src=<%= message.image_url %> ,alt="Image from Telegram ", class="message-image" >
              </li>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </ul>

      <%= form_tag send_message_path,multipart: true, class: 'send-message-form' do %>
        <ul style="padding: 0">
          <%= hidden_field_tag :user_id, params[:user_id].to_i, placeholder: 'Enter user ID' %>
          <li><%= text_field_tag :message_text, '', placeholder: 'Enter your message', :autocomplete => :off, class: "text-field" %></li>
          <li><%= submit_tag 'Send',class: "submit-tag" %></li>
          <li><%= file_field_tag :image %></li>
        </ul>
      <% end %>
    </div>
  </div>

  <script>
    // Scroll to the bottom of the message list on page load
    var messageList = document.getElementById('message-list');
    messageList.scrollTop = messageList.scrollHeight;
  </script>
  </body>

app/views/chat_page/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bot chat</title>
  <link rel="stylesheet" type="text/css" href="<%= asset_path('chat_app.css') %>">

      <div>
      <span style ="position: fixed;
                    top: 0;
                    left: 0;
                    right: 0;
                    font-size: 34px;
                    font-weight: bold;
                    margin-bottom: 20px;
                    background-color: #f2f2f2;
                    border-radius: 10px;
                    padding: 20px;
                    margin: 0;
                    text-align: center;">
        Pick a user to chat with!
      </span>
      
    
    </div>
</head>
<body>
    

<div class="users-list">
    
      <% Message.pluck(:user_id).uniq.each do |user_id| %>
  
        <li>
        <button>
          
          <%= link_to "#{ Message.where.not(user_name: "botson").where(user_id: user_id).order(created_at: :desc).pluck(:user_name).first || "Unknown" }", by_user_path(user_id: user_id), class: "link-primary" %>
        </button>
        </li>
      <% end %>
    </div>

 

  </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Telegrambot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>